"""
Integration tests for the "remove silences" pipeline against REAL speech audio
(as opposed to the synthetic tone fixture used elsewhere) — require the Docker
stack running on http://localhost.

Two fixtures:
  - real_speech_synthetic.mp4: TTS-narrated sentences with designed silence gaps.
  - real_speech_gehrig.mp4: Lou Gehrig's 1939 "Farewell to Baseball" speech
    (public domain, archive.org), with natural pauses from an authentic
    historical recording, including a long noisy/quiet trailing gap.

Both are generated by scripts/create_real_speech_fixtures.sh.

Strategy: rather than hardcoding the exact Whisper transcript text (which can
still shift across model sizes/versions — WHISPER_MODEL defaults to base.en,
but a deployment may override it), each clip is uploaded TWICE: once with
remove_silences=False and once with remove_silences=True. The
two runs must produce byte-identical segment/word TEXT (silence removal must
never alter what was transcribed, only when it's shown), while the WITH-removal
run must have correspondingly shifted-earlier timings and a meaningfully
shorter final render.
"""
from pathlib import Path

import httpx
import pytest

try:
    from .conftest import (
        upload_sample,
        upload_sample_with_silence_removal,
        wait_for_status,
        render_job,
        ffprobe_duration,
        download_to_tempfile,
    )
except ImportError:  # pragma: no cover
    from conftest import (
        upload_sample,
        upload_sample_with_silence_removal,
        wait_for_status,
        render_job,
        ffprobe_duration,
        download_to_tempfile,
    )

BASE_URL = "http://localhost"
FIXTURES_DIR = Path(__file__).parent / "fixtures"

REAL_SPEECH_CLIPS = ["real_speech_synthetic", "real_speech_gehrig"]

# The substantive phrases from the closing lines of Lou Gehrig's speech, as
# verified against a known transcript (Rev.com / SABR's lougehrig.com-derived
# version): "...I consider myself the luckiest man on the face of the earth.
# And I might've been given a bad break, but I've got an awful lot to live
# for. Thank you." Used as a floor on transcription accuracy — a weak model
# (e.g. tiny.en) mangles these into "luck group man" / "bad breath".
GEHRIG_KNOWN_PHRASES = [
    "luckiest man",
    "face of the earth",
    "bad break",
    "awful lot to live for",
    "thank you",
]


def _fixture_path(name: str) -> Path:
    return FIXTURES_DIR / f"{name}.mp4"


def _segments_text(job_id: str) -> list[str]:
    r = httpx.get(f"{BASE_URL}/api/jobs/{job_id}/transcript", timeout=15)
    assert r.status_code == 200
    segments = r.json()["segments"]
    assert segments, "expected at least one transcribed segment for real speech audio"
    return [s["text"] for s in segments]


@pytest.mark.parametrize("clip_name", REAL_SPEECH_CLIPS)
class TestRealSpeechSilenceRemoval:
    def test_transcript_is_non_empty_and_plausible(self, clip_name: str):
        """Sanity check: real speech audio actually produces real words, not
        empty/garbage output — guards against a broken Whisper/VAD config."""
        path = _fixture_path(clip_name)
        if not path.exists():
            pytest.skip(f"Fixture not found: {path}")

        job_id = upload_sample(path)
        wait_for_status(job_id, "ready")
        texts = _segments_text(job_id)
        full_text = " ".join(texts)
        # Real transcribed speech should be made of actual words, not silence.
        assert len(full_text.split()) >= 5

    def test_silence_removal_preserves_text_shifts_timing_shrinks_output(
        self, clip_name: str
    ):
        path = _fixture_path(clip_name)
        if not path.exists():
            pytest.skip(f"Fixture not found: {path}")

        original_duration = ffprobe_duration(path)

        # Baseline run: no silence removal.
        baseline_job = upload_sample(path)
        baseline_status = wait_for_status(baseline_job, "ready")
        assert baseline_status["remove_silences"] is False
        baseline_texts = _segments_text(baseline_job)

        # Silence-removal run: same source file.
        trimmed_job = upload_sample_with_silence_removal(path)
        trimmed_status = wait_for_status(trimmed_job, "ready")
        assert trimmed_status["remove_silences"] is True
        assert trimmed_status["silence_removed_seconds"] is not None
        assert trimmed_status["silence_removed_seconds"] > 1.0
        # Sanity bound: can't have removed more than the original duration.
        assert trimmed_status["silence_removed_seconds"] < original_duration

        trimmed_texts = _segments_text(trimmed_job)

        # The whole point: silence removal must never change WHAT was said,
        # only WHEN it's shown. Same model, same audio content -> identical text.
        assert trimmed_texts == baseline_texts

        # Timings must fit inside the new, shorter timeline.
        trimmed_duration = original_duration - trimmed_status["silence_removed_seconds"]
        r = httpx.get(f"{BASE_URL}/api/jobs/{trimmed_job}/transcript", timeout=15)
        trimmed_segments = r.json()["segments"]
        for seg in trimmed_segments:
            assert seg["start"] >= 0
            assert seg["end"] <= trimmed_duration + 0.5
            for w in seg["words"]:
                assert w["start"] <= w["end"]

        # Segments must still be in chronological order post-remap.
        starts = [s["start"] for s in trimmed_segments]
        assert starts == sorted(starts)

        # Render and confirm the burned output is actually shorter — proves the
        # trim survived into the final video, not just the preview transcript.
        r = render_job(trimmed_job, style="classic")
        assert r.status_code == 202
        wait_for_status(trimmed_job, "complete")

        out_path = download_to_tempfile(trimmed_job)
        try:
            output_duration = ffprobe_duration(out_path)
        finally:
            out_path.unlink(missing_ok=True)

        assert output_duration < original_duration - 1.0
        # Output duration should track the computed trimmed duration closely
        # (re-encode/codec rounding only, not a gross mismatch).
        assert abs(output_duration - trimmed_duration) < 1.0


def test_gehrig_transcript_matches_known_speech_text():
    """Accuracy floor against a known reference transcript (not just
    "non-empty") — catches a model regression (e.g. accidentally shipping
    tiny.en) that produces plausible-looking but wrong text like "luck group
    man" instead of "luckiest man", which the structural tests above can't
    detect since they only compare our own two transcription runs to each
    other, not to ground truth."""
    path = _fixture_path("real_speech_gehrig")
    if not path.exists():
        pytest.skip(f"Fixture not found: {path}")

    job_id = upload_sample(path)
    wait_for_status(job_id, "ready")
    full_text = " ".join(_segments_text(job_id)).lower()

    missing = [p for p in GEHRIG_KNOWN_PHRASES if p not in full_text]
    assert not missing, (
        f"Transcript missing known phrase(s) {missing} from the verified "
        f"speech text — got: {full_text!r}. This usually means WHISPER_MODEL "
        f"is too weak (tiny.en mis-hears 'luckiest' and 'break'); base.en or "
        f"larger is required for this clip."
    )
